### ISSUE TITLE
Task: Managing workflow failures

### ISSUE THREAD

**Issue by boyum** [Tietoevry-Create/gh-actions-workshop#14]
Copilot outline:

# Task 9: Managing Workflow Failures

## 9.1 Identifying Workflow Failures

Set up a failing job: Create a workflow file named failing-job.yml in the .github/workflows directory. Add the following content to the file:

```yml
name: Deliberate Failure

on: [push]

jobs:
  fail_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deliberate Failure
        run: exit 1
```

Review logs: Push your changes and check the Actions tab for the workflow run logs. Look for the failure details.

## 9.2 Debugging Failures

Common issues: Review the logs and identify common failure reasons such as syntax errors, missing dependencies, or incorrect paths.
Troubleshooting steps: Modify the workflow to fix the issues. For example, correct any syntax errors or install missing dependencies.

## 9.3 Implementing Retry Logic

Using `continue-on-error`: Modify the workflow to use the continue-on-error option for the failing step:

```yml
- name: Deliberate Failure
  run: exit 1
  continue-on-error: true
```

Retry strategies: Implement retry logic for transient errors using a separate job or step.

## 9.4 Notifications and Alerts

Setting up notifications: Add a step to send notifications for failed workflows. For example, using the actions-slack action:

```yml
- name: Notify Slack
  if: failure()
  uses: 8398a7/action-slack@v3
  with:
    status: ${{ job.status }}
    author_name: 'GitHub Actions'
    fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

Integrating with external tools: Set up email notifications or integrate with other tools like PagerDuty for alerts on workflow failures.
